"""Her işletme tipi için standart hizmet sözlüğü ve popülerlik ağırlıkları.

LLM'e bırakılmaz — generate_synthetic.py burada tanımlı hizmetlerden
ağırlıklı, tekrarsız örnekleme yapar. Ağırlıklar bir olasılık dağılımı
değil (toplamı 1.0 olmak zorunda değil), göreceli popülerlik puanıdır:
3 = yaygın, 2 = orta sıklıkta, 1 = nadir/özel hizmet.
"""

SERVICE_TAXONOMY: dict[str, dict[str, int]] = {
    "Diş Kliniği": {
        "diş dolgusu": 3,
        "diş çekimi": 3,
        "kanal tedavisi": 3,
        "diş temizliği (detertraj)": 3,
        "implant": 2,
        "ortodonti (tel tedavisi)": 2,
        "diş beyazlatma": 2,
        "protez": 2,
        "pedodonti (çocuk diş hekimliği)": 1,
        "diş eti tedavisi (periodontoloji)": 1,
        "zirkonyum kaplama": 1,
        "lamina (veneer)": 1,
        "gülüş tasarımı": 1,
    },
    "Göz Doktoru": {
        "göz muayenesi": 3,
        "reçeteli gözlük/lens muayenesi": 3,
        "kontakt lens muayenesi": 2,
        "göz tansiyonu ölçümü": 2,
        "göz dibi muayenesi": 2,
        "katarakt değerlendirmesi": 1,
        "şaşılık muayenesi": 1,
        "glokom taraması": 1,
        "lazer görme düzeltme danışmanlığı": 1,
    },
    "Psikolog": {
        "bireysel terapi": 3,
        "kaygı/anksiyete danışmanlığı": 3,
        "online terapi": 2,
        "çift terapisi": 2,
        "aile terapisi": 2,
        "çocuk ve ergen terapisi": 2,
        "stres yönetimi danışmanlığı": 2,
        "grup terapisi": 1,
        "travma sonrası stres danışmanlığı": 1,
        "yeme bozukluğu danışmanlığı": 1,
    },
    "Fizyoterapist": {
        "manuel terapi": 3,
        "egzersiz tedavisi": 3,
        "elektroterapi": 2,
        "spor yaralanması rehabilitasyonu": 2,
        "bel/boyun fıtığı rehabilitasyonu": 2,
        "postür değerlendirmesi": 2,
        "kinesyo bantlama": 1,
        "kuru iğneleme": 1,
        "nörolojik rehabilitasyon": 1,
    },
    "Kuaför": {
        "saç kesimi": 3,
        "fön": 3,
        "saç boyama": 3,
        "saç bakım kürü": 2,
        "röfle/balayaj": 2,
        "keratin bakımı": 2,
        "çocuk saç kesimi": 2,
        "gelin saçı": 1,
        "saç düzleştirme": 1,
        "saç uzatma": 1,
    },
    "Berber": {
        "saç kesimi": 3,
        "sakal tıraşı": 3,
        "sakal şekillendirme": 2,
        "çocuk tıraşı": 2,
        "yüz maskesi": 1,
        "kaş düzeltme": 1,
        "cilt bakımı": 1,
    },
    "Güzellik Salonu": {
        "cilt bakımı": 3,
        "manikür": 3,
        "pedikür": 3,
        "kaş/kirpik tasarımı": 2,
        "makyaj": 2,
        "yüz masajı": 2,
        "vücut masajı": 1,
        "kaş/kirpik lifting": 1,
        "cilt gençleştirme": 1,
        "gelin paketi": 1,
    },
    "Nail Salon": {
        "manikür": 3,
        "pedikür": 3,
        "jel oje": 3,
        "kalıcı oje": 2,
        "protez tırnak": 2,
        "nail art": 1,
        "el/ayak bakımı": 1,
    },
    "Epilasyon Merkezi": {
        "lazer epilasyon": 3,
        "bikini bölgesi epilasyonu": 2,
        "yüz epilasyonu": 2,
        "ağda": 2,
        "IPL epilasyon": 1,
        "erkek epilasyonu": 1,
    },
    "Cilt Bakım Merkezi": {
        "cilt bakımı": 3,
        "cilt analizi": 2,
        "akne tedavisi": 2,
        "peeling": 2,
        "nem bakımı": 2,
        "leke tedavisi": 1,
        "anti-aging bakım": 1,
        "dermapen": 1,
        "mezoterapi": 1,
    },
    "Spor Salonu": {
        "fitness üyeliği": 3,
        "grup dersleri": 2,
        "kişisel antrenörlük": 2,
        "vücut geliştirme programı": 2,
        "pilates": 2,
        "vücut analizi": 1,
        "beslenme danışmanlığı": 1,
        "crossfit dersleri": 1,
        "boks/kickbox dersi": 1,
    },
    "Yüzme Havuzu": {
        "serbest yüzme": 3,
        "yetişkin yüzme kursu": 2,
        "çocuk yüzme kursu": 2,
        "özel yüzme dersi": 1,
        "aquafitness": 1,
        "bebek yüzme kursu": 1,
        "su terapisi (hidroterapi)": 1,
    },
    "Yoga Stüdyosu": {
        "hatha yoga": 3,
        "vinyasa yoga": 2,
        "pilates": 2,
        "meditasyon dersi": 1,
        "hamile yogası": 1,
        "aerial yoga": 1,
        "nefes terapisi": 1,
    },
    "Özel Ders": {
        "matematik dersi": 3,
        "ingilizce dersi": 3,
        "sınav hazırlık dersi": 2,
        "fizik dersi": 2,
        "kimya dersi": 2,
        "online özel ders": 2,
        "YKS/LGS hazırlık": 2,
        "biyoloji dersi": 1,
        "geometri dersi": 1,
    },
    "Dil Kursu": {
        "İngilizce kursu": 3,
        "Almanca kursu": 2,
        "online dil dersi": 2,
        "TOEFL/IELTS hazırlık": 2,
        "İspanyolca kursu": 1,
        "Fransızca kursu": 1,
        "Rusça kursu": 1,
        "Arapça kursu": 1,
        "çocuklar için dil kursu": 1,
    },
    "Sürücü Kursu": {
        "B sınıfı ehliyet eğitimi": 3,
        "direksiyon dersi": 3,
        "trafik kuralları teorik ders": 2,
        "A sınıfı ehliyet eğitimi": 1,
        "motosiklet ehliyeti eğitimi": 1,
        "direksiyon simülatörü dersi": 1,
    },
    "Müzik Kursu": {
        "piyano dersi": 3,
        "gitar dersi": 3,
        "keman dersi": 2,
        "şan dersi": 2,
        "bateri dersi": 2,
        "flüt dersi": 1,
        "saksafon dersi": 1,
        "müzik teorisi dersi": 1,
    },
    "Oto Servis": {
        "periyodik bakım": 3,
        "yağ değişimi": 3,
        "lastik değişimi": 2,
        "akü değişimi": 2,
        "fren bakımı": 2,
        "balata değişimi": 2,
        "rot balans": 1,
        "motor tamiri": 1,
        "elektrik arıza tespiti": 1,
        "ekspertiz": 1,
    },
    "Elektrikçi": {
        "arıza tespiti ve onarımı": 3,
        "priz/anahtar montajı": 2,
        "aydınlatma montajı": 2,
        "elektrik tesisatı kurulumu": 2,
        "kaçak akım kontrolü": 1,
        "topraklama kontrolü": 1,
        "jeneratör bakımı": 1,
    },
    "Tesisatçı": {
        "tesisat tamiri": 3,
        "su kaçağı tespiti": 2,
        "tıkanıklık açma": 2,
        "kombi bakımı": 2,
        "boru döşeme": 1,
        "sıcak su tesisatı": 1,
        "banyo/mutfak tesisatı yenileme": 1,
    },
    "Klima Servisi": {
        "klima bakımı": 3,
        "gaz dolumu": 2,
        "klima montajı": 2,
        "arıza tespiti": 2,
        "split klima montajı": 1,
        "kanal temizliği": 1,
        "VRF sistem bakımı": 1,
    },
    "Telefon Tamiri": {
        "ekran değişimi": 3,
        "batarya değişimi": 3,
        "şarj soketi tamiri": 2,
        "yazılım güncelleme": 1,
        "hoparlör/mikrofon tamiri": 1,
        "kamera tamiri": 1,
        "su hasarı onarımı": 1,
        "veri kurtarma": 1,
    },
    "Veteriner": {
        "aşılama": 3,
        "genel muayene": 3,
        "kısırlaştırma": 2,
        "acil müdahale": 2,
        "diş bakımı": 1,
        "mikroçip uygulama": 1,
        "diyet danışmanlığı": 1,
        "pet pasaportu işlemleri": 1,
    },
    "Fotoğrafçı": {
        "düğün fotoğrafçılığı": 3,
        "portre çekimi": 2,
        "etkinlik fotoğrafçılığı": 2,
        "aile fotoğrafçılığı": 2,
        "ürün fotoğrafçılığı": 1,
        "bebek/yenidoğan çekimi": 1,
        "mezuniyet fotoğrafçılığı": 1,
    },
    "Noter": {
        "vekaletname düzenleme": 3,
        "imza tasdiki": 3,
        "sözleşme onayı": 2,
        "araç satış işlemleri": 2,
        "gayrimenkul satış vaadi sözleşmesi": 1,
        "evlat edinme işlemleri": 1,
    },
    "Muhasebeci": {
        "vergi danışmanlığı": 3,
        "defter tutma": 3,
        "bordro işlemleri": 2,
        "e-fatura işlemleri": 2,
        "mali müşavirlik": 1,
        "KDV beyannamesi": 1,
        "şirket tasfiye işlemleri": 1,
    },
    "Avukat": {
        "danışmanlık": 3,
        "sözleşme hazırlama": 2,
        "boşanma davası": 2,
        "icra takibi": 2,
        "ceza davası": 1,
        "miras hukuku danışmanlığı": 1,
        "iş hukuku davası": 1,
        "gayrimenkul hukuku danışmanlığı": 1,
    },
}
