"""ilk semayi olustur: business_types, businesses, appointment_slots

Revision ID: 123e8e9f7bc4
Revises: 
Create Date: 2026-07-24 17:16:38.378624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '123e8e9f7bc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_group', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type_normalized', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('weighted_rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=False),
    sa.Column('price_max', sa.Integer(), nullable=False),
    sa.Column('appointment_duration_min', sa.Integer(), nullable=False),
    sa.Column('online_available', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('services', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('working_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rich_description', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_normalized'], ['business_types.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_gender'), 'businesses', ['gender'], unique=False)
    op.create_index('ix_businesses_keywords_gin', 'businesses', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_businesses_online_available'), 'businesses', ['online_available'], unique=False)
    op.create_index(op.f('ix_businesses_place_id'), 'businesses', ['place_id'], unique=True)
    op.create_index(op.f('ix_businesses_price_max'), 'businesses', ['price_max'], unique=False)
    op.create_index(op.f('ix_businesses_price_min'), 'businesses', ['price_min'], unique=False)
    op.create_index('ix_businesses_search_vector_gin', 'businesses', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_businesses_tags_gin', 'businesses', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_businesses_type_normalized'), 'businesses', ['type_normalized'], unique=False)
    op.create_index(op.f('ix_businesses_weighted_rating'), 'businesses', ['weighted_rating'], unique=False)
    op.create_table('appointment_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slots_business_start_booked', 'appointment_slots', ['business_id', 'start_time', 'is_booked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_slots_business_start_booked', table_name='appointment_slots')
    op.drop_table('appointment_slots')
    op.drop_index(op.f('ix_businesses_weighted_rating'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_type_normalized'), table_name='businesses')
    op.drop_index('ix_businesses_tags_gin', table_name='businesses', postgresql_using='gin')
    op.drop_index('ix_businesses_search_vector_gin', table_name='businesses', postgresql_using='gin')
    op.drop_index(op.f('ix_businesses_price_min'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_price_max'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_place_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_online_available'), table_name='businesses')
    op.drop_index('ix_businesses_keywords_gin', table_name='businesses', postgresql_using='gin')
    op.drop_index(op.f('ix_businesses_gender'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_table('business_types')
    # ### end Alembic commands ###
